import{S as h,i}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const p="48325175-5a13dcc75d858ba3a77e1c9bf",g="https://pixabay.com/api/";async function u(r,o=1){const s=`${g}?key=${p}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const n=await fetch(s);if(!n.ok)throw new Error("Error while fetching images");return await n.json()}catch(n){throw console.error(n),n}}function y({webformatURL:r,largeImageURL:o,tags:s,likes:n,views:e,comments:t,downloads:a}){return`
      <a href="${o}" class="gallery__item">
          <img src="${r}" alt="${s}" class="gallery__image" />
          <div class="info">
              <p><b>Likes:</b> ${n}</p>
              <p><b>Views:</b> ${e}</p>
              <p><b>Comments:</b> ${t}</p>
              <p><b>Downloads:</b> ${a}</p>
          </div>
      </a>
  `}function L(r){const o=document.querySelector(".gallery");o.innerHTML=r.map(y).join("")}function c(r){const o=document.querySelector(".load-more");r?o.classList.remove("hidden"):o.classList.add("hidden")}function b(r){document.querySelector(".gallery").insertAdjacentHTML("beforeend",r.map(y).join(""))}function f(){const r=document.querySelector(".gallery");r.innerHTML=""}let l=1,d="",m=0;document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector("#search-form"),o=r.querySelector("input"),s=document.createElement("button");s.textContent="Load more",s.classList.add("load-more","hidden"),document.querySelector("main").appendChild(s);const n=new h(".gallery a");r.addEventListener("submit",async e=>{e.preventDefault();const t=o.value.trim();if(!t){i.error({title:"Error",message:"Enter a search query."}),f(),c(!1);return}d=t,l=1,document.querySelector(".loader").classList.remove("hidden");try{const a=await u(d,l);m=a.totalHits,f(),a.hits.length===0?(i.info({title:"No Results",message:"No images found. Try a different query."}),c(!1)):(L(a.hits),n.refresh(),c(a.hits.length===15))}catch{i.error({title:"Error",message:"Failed to load images."})}finally{document.querySelector(".loader").classList.add("hidden")}}),s.addEventListener("click",async()=>{l+=1,document.querySelector(".loader").classList.remove("hidden");try{const e=await u(d,l);b(e.hits),n.refresh(),(l*15>=m||e.hits.length<15)&&(c(!1),i.info({title:"End of results",message:"You've reached the end of search results."}))}catch{i.error({title:"Error",message:"Failed to load images."})}finally{document.querySelector(".loader").classList.add("hidden")}})});
//# sourceMappingURL=index.js.map
