import{i,S as d}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y="48325175-5a13dcc75d858ba3a77e1c9bf",p="https://pixabay.com/api/";async function u(n,o=1){const s=`${p}?key=${y}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const r=await fetch(s);if(!r.ok)throw new Error("Ошибка при загрузке");return await r.json()}catch(r){throw console.error(r),r}}function g({webformatURL:n,largeImageURL:o,tags:s,likes:r,views:e,comments:t,downloads:a}){return`
      <a href="${o}" class="gallery__item">
          <img src="${n}" alt="${s}" class="gallery__image" />
          <div class="info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${e}</p>
              <p><b>Comments:</b> ${t}</p>
              <p><b>Downloads:</b> ${a}</p>
          </div>
      </a>
  `}function f(n){const o=document.querySelector(".gallery");o.innerHTML=n.map(g).join("")}function m(n){const o=document.querySelector(".load-more");n?o.classList.remove("hidden"):o.classList.add("hidden")}let c=1,l="",h=0;document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector("#search-form"),o=n.querySelector("input"),s=document.createElement("button");s.textContent="Load more",s.classList.add("load-more","hidden"),document.querySelector("main").appendChild(s),n.addEventListener("submit",async r=>{r.preventDefault();const e=o.value.trim();if(!e){i.error({title:"Error",message:"Введи запрос"});return}l=e,c=1,document.querySelector(".loader").classList.remove("hidden");try{const t=await u(l,c);h=t.totalHits,t.hits.length===0?i.info({title:"No Results",message:"Неправильно, введи нормальный запрос"}):(f(t.hits),m(!0),new d(".gallery a").refresh())}catch{i.error({title:"Error",message:"Не могу загрузить"})}finally{document.querySelector(".loader").classList.add("hidden")}}),s.addEventListener("click",async()=>{if(c*15>=h){m(!1),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."});return}c+=1,document.querySelector(".loader").classList.remove("hidden");try{const r=await u(l,c);f(r.hits),new d(".gallery a").refresh(),window.scrollBy(0,window.innerHeight)}catch{i.error({title:"Error",message:"Не могу загрузить"})}finally{document.querySelector(".loader").classList.add("hidden")}})});
//# sourceMappingURL=index.js.map
