import{S as g,i as l}from"./assets/vendor-DOBJAGDJ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const a of e.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const p="48325175-5a13dcc75d858ba3a77e1c9bf",L="https://pixabay.com/api/";async function f(r,o=1){const s=`${L}?key=${p}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const n=await fetch(s);if(!n.ok)throw new Error("Error while fetching images");return await n.json()}catch(n){throw console.error(n),n}}function h({webformatURL:r,largeImageURL:o,tags:s,likes:n,views:t,comments:e,downloads:a}){return`
      <a href="${o}" class="gallery__item">
          <img src="${r}" alt="${s}" class="gallery__image" />
          <div class="info">
              <p><b>Likes:</b> ${n}</p>
              <p><b>Views:</b> ${t}</p>
              <p><b>Comments:</b> ${e}</p>
              <p><b>Downloads:</b> ${a}</p>
          </div>
      </a>
  `}function b(r){const o=document.querySelector(".gallery");o.innerHTML=r.map(h).join("")}function d(r){const o=document.querySelector(".load-more");r?o.classList.remove("hidden"):o.classList.add("hidden")}function q(r){document.querySelector(".gallery").insertAdjacentHTML("beforeend",r.map(h).join(""))}function m(){const r=document.querySelector(".gallery");r.innerHTML=""}let c=1,u="",y=0;document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector("#search-form"),o=r.querySelector("input"),s=document.createElement("button");s.textContent="Load more",s.classList.add("load-more","hidden"),document.querySelector("main").appendChild(s);const n=new g(".gallery a");r.addEventListener("submit",async e=>{e.preventDefault();const a=o.value.trim();if(!a){l.error({title:"Error",message:"Enter a search query."}),m(),d(!1);return}u=a,c=1,document.querySelector(".loader").classList.remove("hidden");try{const i=await f(u,c);y=i.totalHits,m(),i.hits.length===0?(l.info({title:"No Results",message:"No images found. Try a different query."}),d(!1)):(b(i.hits),n.refresh(),d(i.hits.length===15))}catch{l.error({title:"Error",message:"Failed to load images."})}finally{document.querySelector(".loader").classList.add("hidden")}});function t(){const e=document.querySelector(".gallery"),{height:a}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*4,behavior:"smooth"})}s.addEventListener("click",async()=>{c+=1,document.querySelector(".loader").classList.remove("hidden");try{const e=await f(u,c);q(e.hits),n.refresh(),t(),(c*15>=y||e.hits.length<15)&&(d(!1),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{l.error({title:"Error",message:"Failed to load images."})}finally{document.querySelector(".loader").classList.add("hidden")}})});
//# sourceMappingURL=index.js.map
